apiVersion: v1
kind: Service
metadata:
  name: mock-pagamentos-svc
spec:
  type: NodePort
  selector:
    app: mock-pagamentos
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 31300
                  